### ISSUE TITLE
Reading string 

### ISSUE THREAD

**Issue by ajitjohnson** [jrobinso/hdf5-indexed-reader#1]
Hi, Thank you for this beautiful package. 

I am new to javascript and using HDF5 files. In Python we do `dataset.asstr()` Would you know how to read strings in js?

In the example file you provided, I presume the file `types`, is a string. Would you be able to show me how you read that into the browser? How can I modify the second line below? 

```
const spatialPostionDataset = await hdfFile.get('/replica10_chr1/types')
const getString = await spatialPostionDataset.asstr();
```

Thank you very much.

**Comment by jrobinso** [comment]
I'm not sure I understand the question, `spatialPostionDataset` in the example is not a string, and cannot be converted to one, it is a 'dataset' in the hdf5 file.   Datasets are converted to javascript objects in the jsfive reader this is built on.  The object has several properties,  'dtype' I think is a string.   I'm not sure what you are referring to by `types`.  

You can get a string representation of `spatialPositionDataset`,  but its not going to be anything useful.  It's probably something like "Object".  

What are you actually trying to do?

**Comment by jrobinso** [comment]
Ahh I see types, that is not a file is an HDF5 path.     And it is not a path to a string, it is an HDF5 "Dataset".

**Comment by ajitjohnson** [comment]
Apologies for my confusing question. Yes `types` is a dataset that contains elements that are of dtype`string`, I was wondering how do you load that into a javascript object. 

In python, I would say: How can I extract/print the contents of the `types` datasets as a list of strings? 

Output be like : ['B3', 'B3', ... ]

Here is how I would do it in Python:

```
with h5py.File('/Users/aj/Downloads/spleen_1chr1rep.indexed.cndb', 'r') as f:
    getString = f['replica10_chr1/types'].asstr()
    print(np.array(getString))
```

Output is: `['B3' 'B3' 'B3' ... 'A1' 'B3' 'B3']`

**Comment by jrobinso** [comment]
No problem, I think I'm the one who was confused.   Well it should be as simple as this

```
const typesDataset = await hdfFile.get('/replica10_chr1/types')
const types = await typesDataset.value
```

However there is a problem, specifically it looks like jsfive (which this is based on) does not support the variable length string type.   I will look into fixing that.  In general conversions to the specified type are handled automatically,  the `value` attribute will return an array, or array of arrays if multidimensional,  of the values.   There is no conversion.

RE extracting and printing array contents as strings, in general you don't need to do anything to a primitive object to "print" it (I assume you mean console.log()),  it will happen automatically.

**Comment by jrobinso** [comment]
Looking at jsfive (itself a port of pyfive),   it looks like variable length strings are not supported for datasets, they are supported for attribute values.   This looks straightforward to fix, I have it on my list.

**Comment by jrobinso** [comment]
OK, that was an easy fix.   The code below will return the variable length string dataset 'types' as an array of strings.  There is no equivalent to the python .asstr(), but I don't think it should be needed.

If building from source you will need to "npm install" again as the jsfive dependency has changed.   

```
        const hdfFile = await openH5File({path: "test/spleen_1chr1rep.indexed.cndb"})
        const typesDataset = await hdfFile.get('/replica10_chr1/types')
        const types = await typesDataset.value

        // types = ['B3', 'B3', ....] etc
```

**Comment by jrobinso** [comment]
BTW there are lots of awaits as many of the functions in this library are asynchronous,  because they go back to the file for something.  Python doesn't really have an equivalent to this.  Without the 'await' you get a Promise for the result.   This is not normal looking javascript (so many awaits), its just the nature of this library.

**Comment by ajitjohnson** [comment]
Wow, I'm incredibly grateful, @jrobinso! The program is now working perfectly, thanks to your help. Your patient explanation of the syntaxes is greatly appreciated.

I didn't realize that you were the creator of IGV. It's truly an honor to have had the opportunity to correspond with you. Thank you once again for your assistance.

**Comment by jrobinso** [comment]
Your welcome.  Ta da,  issue #1 resolved.   There should be some kind of prize or badge for filing the first issue on a project.
