### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by eweitz** [jrobinso/hdf5-indexed-reader#3]
Could you publish this package to NPM?  That would enable wide reuse of this valuable library.

I didn't find `hdf5-indexed-reader` as an NPM package when I recently needed it, so for expediency I published an [org-scoped version of it](https://www.npmjs.com/package/@single-cell-portal/hdf5-indexed-reader) for use in Single Cell Portal.  That enables our particular use case, but it's not ideal for maintainability.  Having the canonical version in this repo published as a standard NPM package seems best for reuse.

Publishing this library at https://www.npmjs.com/package/hdf5-indexed-reader would improve that.

**Comment by jrobinso** [comment]
Sure, its published here: https://www.npmjs.com/package/hdf5-indexed-reader

I wasn't aware anyone was using this.  Glad you find it useful.   The driving use case was this project, which has hdf5 files on the order of a terrabyte or more:  https://github.com/igvteam/spacewalk
